# Generated by Django 5.0.1 on 2024-02-29 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Логин не удовлетворяет требованиям', regex='^[a-zA-Z0-9-]+$')])),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Пароль не удовлетворяет требованиям', regex='^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{6,100}$')])),
                ('countryCode', models.CharField(max_length=3)),
                ('isPublic', models.BooleanField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Телефон не удовлетворяет требованиям', regex='^\\+[\\d]+$')])),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
