# Generated by Django 5.0.1 on 2024-02-29 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodel_countrycode_alter_usermodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
