# Generated by Django 5.0.1 on 2024-02-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_friends_addedat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
