# Generated by Django 5.0.1 on 2024-02-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='countries',
            table='countries',
        ),
    ]
