# Generated by Django 5.0.1 on 2024-03-01 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_countries_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='alpha2',
            field=models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2}S')]),
        ),
        migrations.AlterField(
            model_name='countries',
            name='alpha3',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{3}S')]),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='countries',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
